### ISSUE TITLE
Error: pkg_resources.DistributionNotFound: The 'impacket' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by nullcult** [maaaaz/impacket-examples-windows#5]
Trying to follow your guide on compiling the binaries and am constantly getting the error below when i run the complied binary. I've searched everywhere but I can't find any hints. What could I be doing wrong? 

```
Traceback (most recent call last):
  File "wmiexec.py", line 32, in <module>
  File "c:\users\root\appdata\local\temp\pip-install-bmnnbc\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 391, in load_module
  File "site-packages\impacket-0.9.22.dev1+20200327.103853.7e50589-py2.7.egg\impacket\version.py", line 11, in <module>
  File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 900, in require
  File "site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'impacket' distribution was not found and is required by the application
[3336] Failed to execute script wmiexec
```

**Comment by maaaaz** [comment]
I have never had this bug before as this `get_distribution` code is [quite recent](https://github.com/SecureAuthCorp/impacket/commit/c33bed05f523d114d3eb9db1de9b317dc7a4dc82#diff-a5339127ef49a305fc0c8029a9ec9689).

It seems to be an common issue related to PyInstaller not copying metadata before packaging, you can fix it by creating a specific hook for impacket, like documented [here](https://github.com/pyinstaller/pyinstaller/issues/1713) and [here](https://stackoverflow.com/a/52898981).
